youxin:
  service:
    fetchRegisterUrl: http://risk-meta-gateway1.test.rrdbg.com,http://risk-meta-gateway2.test.rrdbg.com,http://risk-meta-gateway3.test.rrdbg.com
#    fetchRegisterUrl: http://10.205.11.82:8090
    retryTime: 3

poll:
  server:
    flag: true
    corn: 0/30 * * * * ?